language: c

sudo: false

addons:
  apt:
    packages:
      - doxygen

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
  - arduino --install-library "Universal Inputs"
  - arduino --install-library "ArduinoUnit"

  - ln -s $PWD/AliceFirmware $HOME/arduino_ide/libraries/AliceFirmware
  - ln -s $PWD/AliceFirmwareTests $HOME/arduino_ide/libraries/AliceFirmwareTests

  - git clone https://github.com/greiman/SdFat.git sdfat
  - mv $PWD/sdfat/SdFat $HOME/arduino_ide/libraries/SdFat
  - rm -rf sdfat

script:
  - build_platform leonardo
  - build_platform arduino:avr:mega
  - doxygen

notifications:
  email:
    on_success: change
    on_failure: change
