language: c

sudo: false

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - ln -s $PWD/AliceLib $HOME/arduino_ide/libraries/AliceLib
  - ln -s $PWD/AliceNextionUI $HOME/arduino_ide/libraries/AliceNextionUI

install:
  - arduino --install-library "Universal Inputs"
  - arduino --install-library "NeoNextion"

script:
  - build_platform leonardo
  - build_platform arduino:avr:mega

notifications:
  email:
    on_success: change
    on_failure: change
