language: c

sudo: false

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
  - ln -s AliceLib $HOME/arduino_ide/libraries/AliceLib

install:
  - arduino --install-library "ArduinoUniversalInput"
  
script:
  - build_main_platforms
  
notifications:
  email:
    on_success: change
    on_failure: change