language: python

python:
  - "2.7"

sudo: false

cache:
  directories:
    - "~/.platformio"

addons:
  apt:
    packages:
      - doxygen

install:
  - pip install -U platformio

script:
  - yes | platformio run --project-dir ./firmware
  - doxygen

notifications:
  email:
    on_success: change
    on_failure: change
